server:
  port: 8001

spring:
  application:
    name: webstore
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  resources:
    static-locations: classpath:/resources/
  datasource:
    url: jdbc:mysql://localhost:3306/webstore
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        format_sql: true
  liquibase:
    change-log: classpath:db/db-changelog-master.xml

logging:
  level:
    org: INFO, ERROR
    liquibase: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: ../logs/${spring.application.name}.log